<?php

use Illuminate\Database\Seeder;

class CocktailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cocktails')->insert([
            [
                'name' => 'ジントニック',
                'glass_id' => '1',
                'taste_id' => '4',
                'technique_id' => '2',
                'strength_id' => '2',
                'how_to' => 'グラスに氷を入れてジン注ぎ、その後冷えたトニック・ウォーターでグラスを満たし、炭酸が抜けないよう軽くステアする。最後にカットしたライムを飾り付ける。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'マティーニ',
                'glass_id' => '1',
                'taste_id' => '3',
                'technique_id' => '2',
                'strength_id' => '3',
                'how_to' => 'ジンとドライベルモットをミキシンググラスでステアし、グラスに注ぐ。オリーブをカクテルピックに刺して沈め、仕上げにレモンピールをふる。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ホワイトレディ',
                'glass_id' => '2',
                'taste_id' => '4',
                'technique_id' => '3',
                'strength_id' => '3',
                'how_to' => 'シェーカーにすべての材料と氷を入れてシェイクし、グラスに注ぐ。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ギムレット',
                'glass_id' => '2',
                'taste_id' => '3',
                'technique_id' => '3',
                'strength_id' => '3',
                'how_to' => 'シェーカーにすべての材料と氷を入れてシェイクし、グラスに注ぐ。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ジンバック',
                'glass_id' => '1',
                'taste_id' => '2',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスに氷を入れてジンとジンジャーエールでグラスを満たし、炭酸が抜けないよう軽くステアする。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ジンリッキー',
                'glass_id' => '1',
                'taste_id' => '3',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスにカットしたライムを搾り入れ、そのままライムの実もグラスに入れる。その後、氷をグラスに入れてジンを注ぎ入れる。最後に炭酸水でグラスを満たし、軽くステア（混ぜる）して、マドラーを添える。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ジンライム',
                'glass_id' => '1',
                'taste_id' => '1',
                'technique_id' => '1',
                'strength_id' => '1',
                'how_to' => 'グラスにジンとライム・ジュースと氷を入れてステア（混ぜる）する。最後にカットしたライムを飾り付ける。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'カンパリ・カクテル',
                'glass_id' => '2',
                'taste_id' => '2',
                'technique_id' => '2',
                'strength_id' => '3',
                'how_to' => 'すべての材料をミキシンググラスでステアし、グラスに注ぐ。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ブラッディメアリー',
                'glass_id' => '1',
                'taste_id' => '2',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスに氷とすべての材料を入れてステア（混ぜる）する。好みで野菜スティックやレモンを添える。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'カミカゼ',
                'glass_id' => '3',
                'taste_id' => '4',
                'technique_id' => '3',
                'strength_id' => '3',
                'how_to' => 'すべての材料をミキシンググラスでステアし、グラスに注ぐ。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'スクリュードライバー',
                'glass_id' => '1',
                'taste_id' => '2',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスに氷を入れてウォッカ注ぎ、その後オレンジ・ジュースでグラスを満たし、ステア（混ぜる）する。最後にマドラーを添える。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ソルティドッグ',
                'glass_id' => '3',
                'taste_id' => '2',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスの縁をレモンで濡らし、塩をつけてスノースタイルにする。その後ウォッカとグレープフルーツ・ジュースをグラスに注ぎステア（混ぜる）する。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'バラライカ',
                'glass_id' => '2',
                'taste_id' => '4',
                'technique_id' => '3',
                'strength_id' => '4',
                'how_to' => 'グラスの縁をレモンで濡らし、塩をつけてスノースタイルにする。その後ウォッカとグレープフルーツ・ジュースをグラスに注ぎステア（混ぜる）する。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ブルドッグ',
                'glass_id' => '3',
                'taste_id' => '2',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスに氷を入れてウォッカ注ぎ、その後グレープフルーツ・ジュースでグラスを満たし、ステア（混ぜる）する。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'モスコミュール',
                'glass_id' => '1',
                'taste_id' => '2',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスに氷を入れてウォッカとコーディアル・ライム・ジュース注ぎ、その後ジンジャーエールでグラスを満たし、軽くステア（混ぜる）する。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ビッグアップル',
                'glass_id' => '1',
                'taste_id' => '1',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスに氷とすべての材料を入れてステア（混ぜる）する。仕上げに切ったリンゴをグラスに飾り付けても良い。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ウォッカリッキー',
                'glass_id' => '1',
                'taste_id' => '3',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスにカットしたライムを搾り入れ、そのままライムの実もグラスに入れる。その後、氷をグラスに入れてウォッカを注ぎ入れる。最後に炭酸水でグラスを満たし、軽くステア（混ぜる）して、マドラーを添える。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],[
                'name' => 'ウォッカトニック',
                'glass_id' => '1',
                'taste_id' => '2',
                'technique_id' => '1',
                'strength_id' => '2',
                'how_to' => 'グラスに氷を入れてウォッカ注ぎ、その後冷えたトニック・ウォーターでグラスを満たし、炭酸が抜けないよう軽くステアする。',
                'authority' => '1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(), 
            ],
        ]);
    }
}
